
name: Reject Pull Request if File Modified
on:
  pull_request:
    branches: [ "${{ github.base_ref }}" ]


jobs:
  check_codeowners_modification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # This fetches your repository's code

      - name: Fetch origin
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Git Diff CODEOWNERS
        run: 
          if git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep "CODEOWNERS"; then
            echo "CODEOWNERS file has been modified. Rejecting the pull request."
